SELECT * FROM PIO_AML_CUSTOMERS where aml_scenario_code ='1782750712001428'
SELECT * FROM PIO_AML_CUSTOMERS_DET where aml_scenario_code ='1782750712001428'

SELECT * from pio_transactions where cus_num = '20210168'

DELETE FROM PIO_AML_CUSTOMERS
DELETE FROM PIO_AML_CUSTOMERS_DET


DELETE FROM PIO_AML_SCENARIO
DELETE FROM PIO_AML_RULES
DELETE FROM PIO_AML_SCENARIO_RULES
DELETE FROM PIO_AML_RULES_DETAILS

SELECT * FROM PIO_AML_SCENARIO
SELECT * FROM PIO_AML_RULES
SELECT * FROM PIO_AML_SCENARIO_RULES
SELECT * FROM PIO_AML_RULES_DETAILS


SELECT * FROM PIO_AML_PARAMETERS
SELECT * FROM PIO_AML_TABLES
SELECT * FROM PIO_AML_COLUMNS where COLUMN_NAME = 'TRA_AMT'
SELECT * FROM PIO_LTG_DEFINITION

PIO_AML_AGGREGATIONS






















