SET DEFINE OFF;
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('0', 'LTG  CODE', '2', '29', '0', 
    '0', '1', 'LTG CODE');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('1', 'Transaction Type', '3', '9', '0', 
    '0', '1', '??? ??????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('2', 'Number Of Transaction', '3', '28', '0', 
    '0', '6', '??? ???????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('3', 'OPEN DATE', '1', '17', '0', 
    '0', '1', '????? ??? ??????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('4', 'EQU Bal', '1', '1', '0', 
    '0', '4', '?????? ??????? ????????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('5', ' Transaction Amount', '3', '28', '0', 
    '0', '1', '???? ??????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('6', 'Summation Of Transactions', '3', '28', '0', 
    '0', '4', '???? ?????? ??????? ????????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('7', 'Customer Class', '4', '16', '0', 
    '0', '1', '????? ??????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('8', 'Acc Nature', '1', '7', '1', 
    '0', '1', '????? ??????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('9', 'Customer Gender', '4', '23', '0', 
    '0', '1', '?????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('10', 'Marital Status', '4', '26', '0', 
    '0', '1', '?????? ??????????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('11', 'Customber Profession', '4', '25', '0', 
    '0', '1', '??????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('100', 'Branch City Location ', '5', '100', '0', 
    '0', '1', '???? ?????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('101', 'Customer City Location', '4', '101', '0', 
    '0', '1', '???? ??????? ??????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('102', 'MONTHLY_EXP_AMT_INCOME', '4', '102', '0', 
    '0', '1', '????? ?????? ????????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('103', 'Account Day Date', '1', '103', '0', 
    '0', '1', '????? ??????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('104', 'Individual Corporate Indicator', '4', '104', '0', 
    '0', '1', '???? ?????-?????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('105', 'MONTHLY_EXP_AMT_WITHDRAWAL', '4', '105', '0', 
    '0', '1', '????? ?????? ???????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('106', 'Customer Risk Level', '4', '106', '0', 
    '0', '1', '????? ????? ???????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('107', 'Number of Beneficiary/Outward', '3', '107', '0', 
    '0', '6', ' ??? ???????? / ??????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('14', 'Transaction Date', '3', '3', '0', 
    '0', '3', '????? ??????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('112', 'Maturity date for loans', '6', '111', '0', 
    '0', '3', '????? ????????? ??????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('111', 'Maturity date for deposits', '7', '110', '0', 
    '0', '3', '????? ????????? ???????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('113', 'CLOSED_DATE', '1', '112', '0', 
    '0', '1', '????? ??? ?????? ');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('114', 'Account Equivalent  Balance-LGM', '1', '1', '1', 
    '1', '4', '?????? ??????? ????????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('108', ' Black List Flag :1 yes ', '4', '113', '0', 
    '0', '1', '??????? ???????:1???');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('109', 'Last Transaction Amount', '3', '108', '0', 
    '0', '4', '???? ??? ???? ?? ????? ??????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT)
 Values
   ('110', 'Last Equ. Transaction Amount', '3', '109', '0', 
    '0', '4', '???? ??????? ???? ???? ?? ????? ??????');
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   ('117', 'COUNT BRANCH', '3', '2658', '0', 
    '0', '6', 'COUNT BRANCH', 12, TO_DATE('3/7/2026', 'MM/DD/YYYY'), 
    12, TO_DATE('3/7/2026', 'MM/DD/YYYY'));

Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   ('116', 'count transactions', '3', '120', '0', 
    '0', '6', 12, TO_DATE('3/7/2026', 'MM/DD/YYYY'), 12, 
    TO_DATE('3/7/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   ('118', 'STATUS ACCT', '1', '1478', '0', 
    '0', '1', 'STATUS ACCT', 12, TO_DATE('3/12/2026', 'MM/DD/YYYY'), 
    12, TO_DATE('3/12/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   ('119', 'DAY DATE', '1', '59876', '0', 
    '0', '3', 'DAY_DATE', 12, TO_DATE('4/9/2026', 'MM/DD/YYYY'), 
    12, TO_DATE('4/9/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   ('123', 'early payment', '1', '257896', '0', 
    '0', '1', '????? ????', 12, TO_DATE('4/12/2026', 'MM/DD/YYYY'), 
    12, TO_DATE('4/12/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   ('120', 'benf_country', '3', '5687', '0', 
    '0', '1', 'benf_country', 12, TO_DATE('4/11/2026', 'MM/DD/YYYY'), 
    12, TO_DATE('4/11/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   ('121', 'issu_country', '3', '5873', '0', 
    '0', '1', 'issu_country', 12, TO_DATE('4/11/2026', 'MM/DD/YYYY'), 
    12, TO_DATE('4/11/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   ('122', 'risk country', '9', '160', '0', 
    '0', '1', 'risk country', 12, TO_DATE('4/11/2026', 'MM/DD/YYYY'), 
    12, TO_DATE('4/11/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_PARAMETERS
   (PARAMETER_CODE, PARAMETER_ELEMENT, TABLE_CODE, COLUMN_CODE, LGM_SCENARIO_BASED_FLAG, 
    LGM_GROUP_BASED_FLAG, AGGREGATION_CODE, PARAMETER_ELEMENT_NAT, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   ('124', 'Equvalent average  balance quarter', '1', '11', '1', 
    '0', '5', '????? ?????? ??????? ??? ????? ????? ??????', 18, TO_DATE('7/17/2026', 'MM/DD/YYYY'), 
    18, TO_DATE('7/17/2026', 'MM/DD/YYYY'));
COMMIT;
