SET DEFINE OFF;
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '1', '888890', '1', 
    '=', '''19''', 'AND', 'Inward Clearing Chq', '0', 
    '0', '0', 0, TO_DATE('2/19/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('2/19/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '104', '888890', '2', 
    '=', '2', '-', '2', '0', 
    '0', '0', 0, TO_DATE('2/19/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('2/19/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '2', '888895', '2', 
    '>', '5', 'AND', '5', '0', 
    '0', 100, '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '6', '888895', '3', 
    '>=', '45000000', '-', '45000000', '0', 
    '0', 100, '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '0', '888891', '1', 
    '=', '''730''', 'AND', 'CR', '0', 
    '0', '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '2', '888891', '2', 
    '>', '2', 'AND', '2', '0', 
    '0', 100, '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '6', '888891', '3', 
    '>=', '45000000', '-', '45000000', '0', 
    '0', 100, '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '0', '888892', '1', 
    '=', '''730''', 'AND', 'CR', '0', 
    '0', '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '2', '888892', '2', 
    '>', '2', 'AND', '2', '0', 
    '0', 100, '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '6', '888892', '3', 
    '>=', '45000000', '-', '45000000', '0', 
    '0', 100, '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '0', '888894', '1', 
    '=', '''730''', 'AND', 'CR', '0', 
    '0', '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '2', '888894', '2', 
    '>', '3', 'AND', '3', '0', 
    '0', 100, '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '6', '888894', '3', 
    '>=', '45000000', '-', '45000000', '0', 
    '0', 100, '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '1', '888895', '1', 
    'IN', '''101'',''102'',''103'',''107'',''108'',''109'',''124'',''142'',''143'',''144'',''275'',''997'',''998''', 'AND', 'Cash Dep,Cash Dep. In Capital,Cash Dep. States,A/C to A/C in Br.,A/C to A/C in City,A/C to A/C In States,Outward Clearing,Multi Credit in Br.,Multi Credit in City,Multi Credit O. City,SIRAG (RTGS),Swift Multi Transfer,Inward Swift-Multipl', '0', 
    '0', '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '1', '888896', '1', 
    'IN', '''213'',''214'',''215''', 'AND', 'Outward Swift AP,Cash W/D no limitati,Outward Swift CAD', '0', 
    '0', '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '104', '888896', '2', 
    '=', '1', 'AND', '1', '0', 
    '0', '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '6', '888896', '3', 
    '>=', '45000000', '-', '45000000', '0', 
    '0', 100, '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '1', '888897', '1', 
    'IN', '''261'',''262'',''263''', 'AND', 'Master Card Withdraw,Master Cards Purchas,Master Cards Reload', '0', 
    '0', '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '2', '888897', '2', 
    '>=', '2', 'AND', '2', '0', 
    '0', 100, '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '1', '888898', '1', 
    'IN', '''886'',''889'',''997'',''998'',''999''', 'AND', 'Tadawoul NEW Trx 2,Tadawoul Trx 2,Swift Multi Transfer,Inward Swift-Multipl,Inward Swift(single)', '0', 
    '0', '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '2', '888898', '2', 
    '>', '1', 'AND', '1', '0', 
    '0', 100, '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '104', '888898', '3', 
    '=', '2', 'AND', '2', '0', 
    '0', '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '6', '888898', '4', 
    '>=', '2000000', '-', '2000000', '0', 
    '0', 100, '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '0', '888893', '1', 
    '=', '''731''', 'AND', 'DR', '0', 
    '0', '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '2', '888893', '2', 
    '>', '3', 'AND', '3', '0', 
    '0', 100, '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '6', '888893', '3', 
    '>=', '45000000', '-', '45000000', '0', 
    '0', 100, '0', 0, TO_DATE('2/27/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('2/27/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMBINED_RULE, USE_SD_FLAG, SD_PERIOD_TYPE, COMPARISON_PARAMTER, 
    FROM_PARAM_PERC, TO_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '6', '888902', '1', 
    '>=', '-', '0', '0', '102', 
    100, 100, '0', 0, TO_DATE('3/7/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('3/7/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '0', '888903', '1', 
    '=', '''730''', 'AND', 'CR', '0', 
    '0', '0', 0, TO_DATE('3/7/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('3/7/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '116', '888903', '2', 
    '>', '0', 'AND', '0', '0', 
    '0', 100, '0', 0, TO_DATE('3/7/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('3/7/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '6', '888903', '3', 
    '>=', '45000000', '-', '45000000', '0', 
    '0', 100, '0', 0, TO_DATE('3/7/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('3/7/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '0', '888904', '1', 
    '=', '''731''', 'AND', 'DR', '0', 
    '0', '0', 0, TO_DATE('3/7/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('3/7/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '116', '888904', '2', 
    '>', '0', 'AND', '0', '0', 
    '0', 100, '0', 0, TO_DATE('3/7/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('3/7/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '6', '888904', '3', 
    '>=', '45000000', '-', '45000000', '0', 
    '0', 100, '0', 0, TO_DATE('3/7/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('3/7/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '0', '888910', '1', 
    '=', '''730''', 'AND', 'CR', '0', 
    '0', '0', 0, TO_DATE('4/9/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('4/9/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '6', '888910', '2', 
    '>=', '45000000', '-', '45000000', '0', 
    '0', 100, '0', 0, TO_DATE('4/9/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('4/9/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '0', '888911', '1', 
    '=', '''730''', 'AND', 'CR', '0', 
    '0', '0', 0, TO_DATE('4/9/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('4/9/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMBINED_RULE, USE_SD_FLAG, SD_PERIOD_TYPE, COMPARISON_PARAMTER, 
    SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '3', '888911', '2', 
    '=', 'AND', '0', '0', '103', 
    '0', 0, TO_DATE('4/9/2026', 'MM/DD/YYYY'), 0, TO_DATE('4/9/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '6', '888911', '3', 
    '>=', '45000000', '-', '45000000', '0', 
    '0', 100, '0', 0, TO_DATE('4/9/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('4/9/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '1', '888916', '1', 
    '=', '''269''', 'AND', 'BBS to EBS (BBAN)', '0', 
    '0', '0', 0, TO_DATE('7/17/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('7/17/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '2', '888916', '2', 
    '>=', '10', 'AND', '10', '0', 
    '0', 100, '0', 0, TO_DATE('7/17/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('7/17/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '6', '888916', '3', 
    '>=', '45000000', '-', '45000000', '0', 
    '0', 100, '0', 0, TO_DATE('7/17/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('7/17/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '1', '888917', '1', 
    '=', '''270''', 'AND', 'EBS to BBS (BBAN)', '0', 
    '0', '0', 0, TO_DATE('7/17/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('7/17/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '2', '888917', '2', 
    '>=', '10', '-', '10', '0', 
    '0', 100, '0', 0, TO_DATE('7/17/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('7/17/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '5', '888908', '1', 
    '>=', '45000000', '-', '45000000', '0', 
    '0', 100, '0', 0, TO_DATE('3/16/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('3/16/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '1', '888918', '1', 
    'IN', '''265'',''269'',''704'',''705'',''275'',''277'',''106'',''107'',''108'',''109'',''116'',''124'',''126'',''127'',''139'',''140'',''141'',''155'',''213'',''214'',''215''', '-', 'A/C to A/C Internal,BBS to EBS (BBAN),mPAY TRANSFER,SUBA OUTWARD TRANSFE,SIRAG outward(RTGS),Pay SIRAG outward(RT,Cash W/D Out City,A/C to A/C in Br.,A/C to A/C in City,A/C to A/C In States,Demand Draft in Br.,Outward Clearing,Hse. Chq. dep in Br.,Hse. Ch. dep in City,Multi Debit in Br.,Mutli Debit in City,Mutli Debit Out City,Outward swift A/C,Outward Swift AP,Cash W/D no limitati,Outward Swift CAD', '0', 
    '0', '0', 0, TO_DATE('7/17/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('7/17/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, FROM_PARAM_PERC, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, 
    UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '117', '888905', '1', 
    '>', '3', '-', '3', '0', 
    '0', 100, '0', 0, TO_DATE('3/7/2026', 'MM/DD/YYYY'), 
    0, TO_DATE('3/7/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '0', '888912', '1', 
    '=', '''27''', 'AND', 'Incoming Transfer transaction', '0', 
    '0', '0', 0, TO_DATE('4/11/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('4/11/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMBINED_RULE, USE_SD_FLAG, SD_PERIOD_TYPE, COMPARISON_PARAMTER, 
    SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '121', '888912', '2', 
    '=', '-', '0', '0', '122', 
    '0', 0, TO_DATE('4/11/2026', 'MM/DD/YYYY'), 0, TO_DATE('4/11/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '0', '888913', '1', 
    '=', '''26''', 'AND', 'Outgoing Transfer transaction', '0', 
    '0', '0', 0, TO_DATE('4/11/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('4/11/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMBINED_RULE, USE_SD_FLAG, SD_PERIOD_TYPE, COMPARISON_PARAMTER, 
    SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '120', '888913', '2', 
    '=', '-', '0', '0', '122', 
    '0', 0, TO_DATE('4/11/2026', 'MM/DD/YYYY'), 0, TO_DATE('4/11/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '1', '888914', '1', 
    'IN', '''101'',''102'',''103''', 'AND', 'Cash Dep,Cash Dep. In Capital,Cash Dep. States', '0', 
    '0', '0', 0, TO_DATE('4/11/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('4/11/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMBINED_RULE, USE_SD_FLAG, SD_PERIOD_TYPE, SAME_CUST_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '113', '888914', '2', 
    'IS NOT NULL', 'AND', '0', '0', '0', 
    0, TO_DATE('4/11/2026', 'MM/DD/YYYY'), 0, TO_DATE('4/11/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMBINED_RULE, USE_SD_FLAG, SD_PERIOD_TYPE, COMPARISON_PARAMTER, 
    SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE)
 Values
   (729, 1, '14', '888914', '3', 
    '<=', '-', '0', '0', '113', 
    '0', 0, TO_DATE('4/11/2026', 'MM/DD/YYYY'), 0, TO_DATE('4/11/2026', 'MM/DD/YYYY'));
Insert into BI_DWH.PIO_AML_RULES_DETAILS
   (COUNTRY_CODE, INST_CODE, PARAMETER_CODE, RULE_CODE, RULE_SEQ, 
    RULE_OPERATOR, COMPARISON_VALUE_FROM, COMBINED_RULE, COMPARISON_VALUE_FROM_DES, USE_SD_FLAG, 
    SD_PERIOD_TYPE, SAME_CUST_FLAG, CREATED_BY, CREATED_DATE, UPDATED_BY, 
    UPDATED_DATE)
 Values
   (729, 1, '123', '888915', '1', 
    '=', '''1''', '-', '''1''', '0', 
    '0', '0', 0, TO_DATE('4/12/2026', 'MM/DD/YYYY'), 0, 
    TO_DATE('4/12/2026', 'MM/DD/YYYY'));
COMMIT;
