SET DEFINE OFF;
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_TYPE, 
    FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC)
 Values
   (729, 1, '777777', '777777', '3', 
    0, 100, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888908', '1000000', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888891', '1000002', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888905', '1000013', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888890', '1000001', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888896', '1000006', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888895', '1000007', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888897', '1000008', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888898', '1000009', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888892', '1000003', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888893', '1000004', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888894', '1000005', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888902', '1000011', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888903', '1000012', '1', 
    '4', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888904', '1000012', '2', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888910', '1000015', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888911', '1000016', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888915', '1000020', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888916', '1000021', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888912', '1000017', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888913', '1000018', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888914', '1000019', '1', 
    '3', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888917', '1000022', '1', 
    '2', 0, 0, 0, 0);
Insert into BI_DWH.PIO_AML_SCENARIO_RULES
   (COUNTRY_CODE, INST_CODE, AML_RULE_CODE, AML_SCENARIO, RULE_SEQ, 
    RULE_TYPE, FREQUENCY_DAYS, AMT_PERC, MARGIN_PERC, STOP_PERIOD)
 Values
   (729, 1, '888918', '1000022', '2', 
    '3', 0, 0, 0, 0);
COMMIT;
