SET DEFINE OFF;
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, TRANS_WITHOUTTRANS_FLAG, ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '777777', 'Customer Checker \Outside Black LIST ', '????? ????? ???????\???? ??????? ???????', 
    '1', '1', '1', '2', 'M', 
    '1', '0', '1', '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, CREATED_BY, 
    UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000000', '?? ????? ????? ?????? 15,000 ????? ?? ?? ???????', '?? ????? ????? ?????? 15,000 ????? ?? ?? ???????', 
    '1', '0', '0', '1', 'D', 
    '1', '1', '1', '0', 0, 
    12, TO_DATE('3/16/2026', 'MM/DD/YYYY'), '1', '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000002', 'Large sum (credit) transactions (7 days)', 'Large sum (credit) transactions (7 days)', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('2/19/2026', 'MM/DD/YYYY'), 12, TO_DATE('2/19/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000013', 'Large number of visits to different branch offices in the last 30 days', 'Large number of visits to different branch offices in the last 30 days', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('3/7/2026', 'MM/DD/YYYY'), 12, TO_DATE('3/7/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000001', 'Non-Profit Organization', 'Non-Profit Organization', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('2/19/2026', 'MM/DD/YYYY'), 12, TO_DATE('2/19/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000006', 'Internet Banking (30 days)', 'Internet Banking (30 days)', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('2/25/2026', 'MM/DD/YYYY'), 12, TO_DATE('2/25/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, CREATED_BY, 
    UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000007', 'Collective accounts (3 months)', 'Collective accounts (3 months)', 
    '1', '0', '0', '1', 'D', 
    '1', '1', '1', '0', 0, 
    12, TO_DATE('2/25/2026', 'MM/DD/YYYY'), '1', '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000008', 'Credit Cards', 'Credit Cards', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('2/25/2026', 'MM/DD/YYYY'), 12, TO_DATE('2/25/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000009', 'offshore', 'offshore', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('2/25/2026', 'MM/DD/YYYY'), 12, TO_DATE('2/25/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000003', 'Large sum (debit)transactions (7 days)', 'Large sum (debit)transactions (7 days)', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('2/23/2026', 'MM/DD/YYYY'), 12, TO_DATE('2/23/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000004', 'Large sum (debit)transactions (3 months)', 'Large sum (debit)transactions (3 months)', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('2/23/2026', 'MM/DD/YYYY'), 12, TO_DATE('2/23/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000005', 'Large sum (credit)transactions (3 months)', 'Large sum (credit)transactions (3 months)', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('2/23/2026', 'MM/DD/YYYY'), 12, TO_DATE('2/23/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000011', 'Sudden transaction increase', 'Sudden transaction increase', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('3/7/2026', 'MM/DD/YYYY'), 12, TO_DATE('3/7/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000012', 'Rapid (IN/Out) movements of funds (weekly)', 'Rapid (IN/Out) movements of funds (weekly)', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('3/7/2026', 'MM/DD/YYYY'), 12, TO_DATE('3/7/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000015', 'Scenario detects customers (staff) who receive internal transfers, with total amount of 2,000 USD or more (30 days) (1 transaction or more)', 'Scenario detects customers (staff) who receive internal transfers, with total amount of 2,000 USD or more (30 days) (1 transaction or more)', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('4/9/2026', 'MM/DD/YYYY'), 12, TO_DATE('4/9/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000016', 'New customer (customer opening date) with large cash deposits', 'New customer (customer opening date) with large cash deposits', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('4/9/2026', 'MM/DD/YYYY'), 12, TO_DATE('4/9/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000020', 'Early loan repayment, large amount', 'Early loan repayment, large amount', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('4/12/2026', 'MM/DD/YYYY'), 12, TO_DATE('4/12/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000021', '??? ???? ???? ???? ?????? ??? ??????? ??????? ?????? ????? ??? ?????? ?????? ?? ???? ???? ??? BBAN ???? ??? ?? ?????? ???? ???? ??????? ?????? ?????? ?? ????? ?????? ??????? ?? ?????? ??????? ???????? ???????.', '??? ???? ???? ???? ?????? ??? ??????? ??????? ?????? ????? ??? ?????? ?????? ?? ???? ???? ??? BBAN ???? ??? ?? ?????? ???? ???? ??????? ?????? ?????? ?? ????? ?????? ??????? ?? ?????? ??????? ???????? ???????.', 
    '1', '0', '0', '1', 'M', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('7/17/2026', 'MM/DD/YYYY'), 12, TO_DATE('7/17/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000017', 'Countries to be observed (inward)', 'Countries to be observed (inward)', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('4/11/2026', 'MM/DD/YYYY'), 12, TO_DATE('4/11/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000018', 'Countries to be observed (Outward)', 'Countries to be observed (Outward)', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('4/11/2026', 'MM/DD/YYYY'), 12, TO_DATE('4/11/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000019', 'Short-term account', 'Short-term account', 
    '1', '0', '0', '1', 'D', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('4/11/2026', 'MM/DD/YYYY'), 12, TO_DATE('4/11/2026', 'MM/DD/YYYY'), '1', 
    '0');
Insert into BI_DWH.PIO_AML_SCENARIO
   (COUNTRY_CODE, INST_CODE, SCENARIO_CODE, SCENARIO_DES_ENG, SCENARIO_DES_NAT_LAN, 
    ACTIVE_FLAG, EXCLUDE_EXPL_FLAG, USE_WATCHLIST_FLAG, VIOLATION_LEVEL, DEGREE_RISK_FLAG, 
    DEFAULT_SCENARIO_FLAG, RUN_FLAG, APPROVAL_FLAG, GROUP_BY_FLAG, USE_WORLDCHECK_FLAG, 
    CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, TRANS_WITHOUTTRANS_FLAG, 
    ACTIVE_THRESHOLD_CURR_FLAG)
 Values
   (729, 1, '1000022', '??? ???? ????? ??????? ?????? ?? ?????? ?????? ?? ???? ???? ??? ????? ???????? ???? ???? ????? (????? 48 ????)? ?? ??? ??? ??????? ?? ??????? ?????.', '??? ???? ????? ??????? ?????? ?? ?????? ?????? ?? ???? ???? ??? ????? ???????? ???? ???? ????? (????? 48 ????)? ?? ??? ??? ??????? ?? ??????? ?????.', 
    '1', '0', '0', '1', 'M', 
    '0', '1', '1', '1', '0', 
    12, TO_DATE('7/17/2026', 'MM/DD/YYYY'), 12, TO_DATE('7/17/2026', 'MM/DD/YYYY'), '1', 
    '0');
COMMIT;
